services:
  web:
    build: #compilar la imagen a partir del Dockerfile
      context: .. #raiz del proyecto
      dockerfile: deploy/Dockerfile
    container_name: ctportfolio
    ports:
      - "8810:80"
